### ISSUE TITLE
A question about the script

### ISSUE THREAD

**Issue by CharlesYTJ** [xiaogang00/SMG-LLIE#3]
When I run sh test_LOL_real.sh,  the following error occurs. How can I solve it?

(myconda) root@ZWnB9b:/mnt/SMG-LLIE-main# sh test_LOL_real.sh 
/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "scripts/test_LOL_real_image.py", line 19, in <module>
    from training.coach_LOL_real import Coach
  File "/mnt/SMG-LLIE-main/./training/coach_LOL_real.py", line 22, in <module>
    from models.SAG import Discriminator, FullGenerator
  File "/mnt/SMG-LLIE-main/./models/SAG.py", line 12, in <module>
    from models.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/mnt/SMG-LLIE-main/./models/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/mnt/SMG-LLIE-main/./models/op/fused_act.py", line 13, in <module>
    fused = load(
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1124, in load
    return _jit_compile(
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1337, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1418, in _write_ninja_file_and_build_library
    verify_ninja_availability()
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1474, in verify_ninja_availability
    raise RuntimeError("Ninja is required to load C++ extensions")
RuntimeError: Ninja is required to load C++ extensions
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 515) of binary: /root/miniconda3/envs/myconda/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/myconda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
scripts/test_LOL_real_image.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-15_08:15:15
  host      : ZWnB9b
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 515)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by CharlesYTJ** [comment]
I have resolved the issue, and the project is excellent, but the environment is too challenging to configure for me.

**Comment by ArroPer** [comment]
> I have resolved the issue, and the project is excellent, but the environment is too challenging to configure for me.

Hi！
How did you solve it？

**Comment by QiaoYang-CV** [comment]
> I have resolved the issue, and the project is excellent, but the environment is too challenging to configure for me.

Can you share how it was resolved? Indeed this environment is a pain in the ass to run. I will acknowledge you in the appropriate place.
