### ISSUE TITLE
关于test的输出尺寸问题以及训练的显存

### ISSUE THREAD

**Issue by Mayingj** [xiaogang00/SMG-LLIE#6]
您好！非常感谢您的工作。我最近也在进行关于低光增强的工作，在学习和验证您的代码时，我遇到了两个问题，希望您能帮助我！（1）在运行test_SID.sh的时候，我发现，结果输出为512*512，这与实际尺寸是有差别，对比您的文章（关于SID图像的展示似乎也是512*512），我记得SID原始图片的尺寸是960*512，我在transformer_config.py找到了关于尺寸Resize的设置，但是我更改Resize的大小，会出现一系列报错，请问您在代码中是如何调整的？（2）请问您实际占用的显存是多少，我目前只有一张24G显存的显卡，我想要调整进入网络的尺寸，但是在transformer_config.py中进行设置的时候，也会出现许多错误，请问您有什么办法嘛？

**Comment by cshonglei** [comment]
我在测试的时候，也发现输出是512 * 512不是图片原有的尺寸，并且使用提供的权重测试出的结果很低，不知道是不是没有使用正确，请问你测试了吗？ 测试结果和原文一样吗？

**Comment by cshonglei** [comment]
抱歉，看错了训练集，测试结果和论文是一致的

**Comment by cheny00** [comment]
你好，我在运行test_SID.sh、train_SID.sh、test_LOL_real.sh、test_LOL_synthetic.sh文件时，出现了【Error: Cannot find module 'windows-foreground-love'】问题，请教一下该如何正确运行程序呢。

/**********报错信息***************/
[main 2023-11-15T10:09:23.551Z] Error: Cannot find module 'windows-foreground-love'
Require stack:
- C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109751)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at d (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:98)
    at r.load (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:5:1642)
    at o.load (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:4:13621)
    at f (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:9301)
    at Object.errorback (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:9420)
    at o.triggerErrorback (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:4:13915)
    at C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:4:13666
    at r.load (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:5:1659)
    at o.load (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:4:13621)
    at f (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:9301)
    at b._loadModule (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:9429)
    at b._resolve (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:7:452)
    at b.defineModule (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:5524)
    at b._relativeRequire (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:6148)
    at e (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js:6:8479)
    at C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:93:336
    at new Promise (<anonymous>)
    at Le.h (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:93:314)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Le.e (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:92:5700)
    at async C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:92:1424
    at async Le.a (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:92:1266) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Cursor\\resources\\app\\out\\main.js',
    undefined
  ],
  phase: 'loading',
  moduleId: 'windows-foreground-love',
  neededBy: [ '===anonymous3===' ]
}
"E:/project/edge detection/Low-Light Image Enhancement via Structure Modeling and Guidance/SMG-LLIE-main/train_SID.sh"

E:\project\edge detection\Low-Light Image Enhancement via Structure Modeling and Guidance\SMG-LLIE-main>
[main 2023-11-15T10:09:38.387Z] Error: Cannot find module 'windows-foreground-love'
Require stack:
- C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\main.js
-
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:109751)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Le.e (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:92:5700)
    at async C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:92:1424
    at async Le.a (C:\Users\Lenovo\AppData\Local\Programs\Cursor\resources\app\out\vs\code\electron-main\main.js:92:1266) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Lenovo\\AppData\\Local\\Programs\\Cursor\\resources\\app\\out\\main.js',
    undefined
  ],
  phase: 'loading',
  moduleId: 'windows-foreground-love',
  neededBy: [ '===anonymous3===' ]
}

/*************************end*************************/
