### ISSUE TITLE
权重文件失效

### ISSUE THREAD

**Issue by luocha0107** [xiaogang00/SMG-LLIE#8]
作者您好，下载SID_test权重文件的网站好像失效了，会显示连接失败，wget权重网站也是连接失败。您能提供一份权重文件吗

**Comment by xiaogang00** [comment]
您好，已经确认过，链接可以下载，https://drive.google.com/file/d/1pevOfv5VTptfHYiswGEvWE3B-e-vxHPw/view，请检查是否是您网络问题。

**Comment by luocha0107** [comment]
> 您好，已经确认过，链接可以下载，[https://drive.google.com/file/d/1pevOfv5VTptfHYiswGEvWE3B-e-vxHPw/view，请检查是否是您网络问题。](https://drive.google.com/file/d/1pevOfv5VTptfHYiswGEvWE3B-e-vxHPw/view%EF%BC%8C%E8%AF%B7%E6%A3%80%E6%9F%A5%E6%98%AF%E5%90%A6%E6%98%AF%E6%82%A8%E7%BD%91%E7%BB%9C%E9%97%AE%E9%A2%98%E3%80%82)


(smg) root@fc0d8bf8c79f:/data/SMG-LLIE-main# sh train_SID.sh
/opt/conda/envs/smg/lib/python3.8/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
0
/opt/conda/envs/smg/lib/python3.8/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/opt/conda/envs/smg/lib/python3.8/site-packages/torchvision/models/_utils.py:135: UserWarning: Using 'weights' as positional parameter(s) is deprecated since 0.13 and may be removed in the future. Please use keyword parameter(s) instead.
  warnings.warn(
/opt/conda/envs/smg/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://raw.githubusercontent.com/richzhang/PerceptualSimilarity/master/lpips/weights/v0.1/alex.pth" to /root/.cache/torch/hub/checkpoints/alex.pth
Traceback (most recent call last):
  File "/opt/conda/envs/smg/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/conda/envs/smg/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/envs/smg/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/smg/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/smg/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/opt/conda/envs/smg/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/opt/conda/envs/smg/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/opt/conda/envs/smg/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/opt/conda/envs/smg/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/opt/conda/envs/smg/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/train_SID.py", line 115, in <module>
    main()
  File "scripts/train_SID.py", line 50, in main
    coach = Coach(opts, previous_train_ckpt)
  File "/data/SMG-LLIE-main/./training/coach_SID.py", line 154, in __init__
    self.lpips_loss = LPIPS1(net_type=self.opts.lpips_type).to(self.device).eval()
  File "/data/SMG-LLIE-main/./criteria/lpips/lpips.py", line 30, in __init__
    self.lin.load_state_dict(get_state_dict(net_type, version))
  File "/data/SMG-LLIE-main/./criteria/lpips/utils.py", line 17, in get_state_dict
    old_state_dict = torch.hub.load_state_dict_from_url(
  File "/opt/conda/envs/smg/lib/python3.8/site-packages/torch/hub.py", line 746, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/opt/conda/envs/smg/lib/python3.8/site-packages/torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "/opt/conda/envs/smg/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/envs/smg/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/conda/envs/smg/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/conda/envs/smg/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/envs/smg/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/conda/envs/smg/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2938194) of binary: /opt/conda/envs/smg/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/smg/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/smg/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/smg/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/opt/conda/envs/smg/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/opt/conda/envs/smg/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/opt/conda/envs/smg/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/conda/envs/smg/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/smg/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
scripts/train_SID.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-18_11:47:57
  host      : fc0d8bf8c79f
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2938194)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================


会出现这种连接失败的错误，能解答一下吗

**Comment by QiaoYang-CV** [comment]
作者您好，能否给予百度云网盘的链接呢？
